spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

##Cache config
cache:
  url:
    ttl: 24
    max-size: 20

## Security config
app:
  api-key: ${API-KEY}